# Кофигурация с поддоменом и SSL сертификатами в файле nginx_subdomain.conf
# Кофигурация с поддоменом и SSL сертификатами в файле nginx_subdomain.conf
user  root;
worker_processes  1;

events {
}

http {
    server {
        listen       80;
        server_name  aristokrat.by;

        location / {
            proxy_pass http://frontend:3000/;
        }

        location /api/ {
            proxy_pass http://backend:8000/;
        }
    }

    server {
        listen       443 ssl;
        server_name  aristokrat.by;

        ssl_certificate     /etc/letsencrypt/live/aristokrat.by/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/aristokrat.by/privkey.pem;

        location / {
            proxy_pass http://frontend:3000/;
        }

        location /api/ {
            proxy_pass http://backend:8000/;
        }
    }
}